name: Build
on: [push, pull_request]
jobs:
  # Build the game
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.5']
    steps:
    - uses: actions/checkout@v6
    - uses: nhartland/love-build@v1
      id: love-build
      with:
        app_name: 'game'
        love_version: ${{ matrix.love_version }}
        source_dir: 'src'
    # Upload the resulting artifacts
    - uses: actions/upload-artifact@v6
      with:
        name: gng_macos-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v6
      with:
        name: gng_win32-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v6
      with:
        name: gng_win64-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v6
      with:
        name: gng_love-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.love-filename }}
    - uses: actions/upload-artifact@v6
      with:
        name: gng_linux_x86_64-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.linux_x86_64-filename }}

